// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarWarsQuest.Api.Context;

#nullable disable

namespace StarWarsQuest.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523172223_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StarWarsQuest.Api.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("characterid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CharacterId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("CharacterId");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("StarWarsQuest.Api.Models.Quest", b =>
                {
                    b.Property<int>("QuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("questid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<bool>("Ended")
                        .HasColumnType("boolean")
                        .HasColumnName("ended");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("Started")
                        .HasColumnType("boolean")
                        .HasColumnName("started");

                    b.HasKey("QuestId");

                    b.ToTable("quests", (string)null);
                });

            modelBuilder.Entity("StarWarsQuest.Api.Models.QuestAssociations", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("characterid");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer")
                        .HasColumnName("questid");

                    b.Property<int>("SpaceshipId")
                        .HasColumnType("integer")
                        .HasColumnName("spaceshipid");

                    b.HasKey("CharacterId", "QuestId", "SpaceshipId");

                    b.HasIndex("QuestId");

                    b.HasIndex("SpaceshipId");

                    b.ToTable("questassociations", (string)null);
                });

            modelBuilder.Entity("StarWarsQuest.Api.Models.Spaceship", b =>
                {
                    b.Property<int>("SpaceshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("spaceshipid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpaceshipId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("SpaceshipId");

                    b.ToTable("spaceships", (string)null);
                });

            modelBuilder.Entity("StarWarsQuest.Api.Models.QuestAssociations", b =>
                {
                    b.HasOne("StarWarsQuest.Api.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsQuest.Api.Models.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsQuest.Api.Models.Spaceship", "Spaceship")
                        .WithMany()
                        .HasForeignKey("SpaceshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Quest");

                    b.Navigation("Spaceship");
                });
#pragma warning restore 612, 618
        }
    }
}
